language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "tian1iang"
  - git config user.email "598318876@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${REPO_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/tian1iang/tian1iang.github.io.git
